### ISSUE TITLE
googleCalendar@javahelps.com: pip problem

### ISSUE THREAD

**Issue by LinuxOnTheDesktop** [linuxmint/cinnamon-spices-desklets#392]
Well then, tell me how to find that 'UUID' and indeed what a 'UUID' is. I have guessed that the needful information is: 'googleCalendar@javahelps.com'.

```
 * Desklet version/Build date (to be found in "About.." or in "metadata.json"): 2019-01-22. *Why is that text not copy-pastable? One cannot even its window on the screen while doing anything else!*
 * Cinnamon version (cinnamon --version): 4.0.9
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...): 19.1
 * Graphics hardware *and* driver used: Intel UHD Graphics 620; 3.0 Mesa 18.2.2
 * Snippet or attachment of ~/.cinnamon/glass.log
 * Snippet or attachment of ~/.xsession-errors
[xsesh.txt](https://github.com/linuxmint/cinnamon-spices-desklets/files/2824730/xsesh.txt)


 ```

**Notify author of desklet**
@slgobinath

**Issue**

No applet, perhaps because of pip problem.

**Steps to reproduce**

1. Find and follow the instructions on the Spices website.
2. Install prerequisites.
3. Download the applet.
4. Install the applet
5. Authorize the applet with Google.
6. Discover that there is no desklet, perhaps because of this error thrown at stage 2:

```
Installing collected packages: cachetools, google-auth, google-auth-httplib2, uritemplate, google-api-python-client, oauth2client
  Found existing installation: uritemplate 0.6
Cannot uninstall 'uritemplate'. It is a distutils installed project and thus we cannot accurately determine which files belong to it which would lead to only a partial uninstall.
```

**Expected behaviour**

I expect no errors during installation (pre-installation . .) and I expect to see the applet.

**Other information**

I would like this applet to work because the Rainlendar calendar program works poorly.

I tried uninstalling `python3-uritemplate`; so doing removed two other packages. I didn't get anywhere - though I haven't yet logged out and back in - and I think the reason might be a clash between apt dependencies and pip, or something like that.

**Comment by slgobinath** [comment]
Hi,
I guess you get this error when you execute the following command:
```
sudo pip3 install --upgrade python-dateutil google-api-python-client oauth2client
```

If so, please add `--ignore-installed` argument to the command as shown below:
```
sudo pip3 install --ignore-installed python-dateutil google-api-python-client oauth2client
```

After the installation, please make sure that the `google_calendar.py` works as expected by executing the following commands:
```
cd ~/.cinnamon/configs/googleCalendar@javahelps.com
python3 ~/.local/share/cinnamon/desklets/googleCalendar@javahelps.com/py/google_calendar.py --list-calendars
```

Even though, I couldn't reproduce this problem I hope the above solution should fix it.

**Comment by LinuxOnTheDesktop** [comment]
Thank you. The applet still does not work. Here is my output.

```
sudo pip3 install --ignore-installed python-dateutil google-api-python-client oauth2client
[Various errors about sudo, ending with: 'If executing pip with sudo, you may want sudo's -H flag.']
Collecting python-dateutil
  Downloading https://files.pythonhosted.org/packages/74/68/d87d9b36af36f44254a8d512cbfc48369103a3b9e474be9bdfe536abfc45/python_dateutil-2.7.5-py2.py3-none-any.whl (225kB)
    100% |████████████████████████████████| 235kB 4.7MB/s 
Collecting google-api-python-client
  Downloading https://files.pythonhosted.org/packages/55/e9/e8fb2e3a031cb69b9524b80a92b126665d9a17421700a219555e3233ab6a/google_api_python_client-1.7.8-py3-none-any.whl (56kB)
    100% |████████████████████████████████| 61kB 10.6MB/s 
Collecting oauth2client
  Downloading https://files.pythonhosted.org/packages/95/a9/4f25a14d23f0786b64875b91784607c2277eff25d48f915e39ff0cff505a/oauth2client-4.1.3-py2.py3-none-any.whl (98kB)
    100% |████████████████████████████████| 102kB 5.1MB/s 
Collecting six>=1.5 (from python-dateutil)
  Downloading https://files.pythonhosted.org/packages/73/fb/00a976f728d0d1fecfe898238ce23f502a721c0ac0ecfedb80e0d88c64e9/six-1.12.0-py2.py3-none-any.whl
Collecting httplib2<1dev,>=0.9.2 (from google-api-python-client)
  Downloading https://files.pythonhosted.org/packages/ce/ed/803905d670b52fa0edfdd135337e545b4496c2ab3a222f1449b7256eb99f/httplib2-0.12.0.tar.gz (218kB)
    100% |████████████████████████████████| 225kB 5.6MB/s 
Collecting uritemplate<4dev,>=3.0.0 (from google-api-python-client)
  Downloading https://files.pythonhosted.org/packages/e5/7d/9d5a640c4f8bf2c8b1afc015e9a9d8de32e13c9016dcc4b0ec03481fb396/uritemplate-3.0.0-py2.py3-none-any.whl
Collecting google-auth-httplib2>=0.0.3 (from google-api-python-client)
  Downloading https://files.pythonhosted.org/packages/33/49/c814d6d438b823441552198f096fcd0377fd6c88714dbed34f1d3c8c4389/google_auth_httplib2-0.0.3-py2.py3-none-any.whl
Collecting google-auth>=1.4.1 (from google-api-python-client)
  Downloading https://files.pythonhosted.org/packages/4e/85/71b2dfbf5b4241cd031cc333ed71f90a271074a97cb2c517bb65f07a1a90/google_auth-1.6.2-py2.py3-none-any.whl (73kB)
    100% |████████████████████████████████| 81kB 8.4MB/s 
Collecting pyasn1>=0.1.7 (from oauth2client)
  Downloading https://files.pythonhosted.org/packages/7b/7c/c9386b82a25115cccf1903441bba3cbadcfae7b678a20167347fa8ded34c/pyasn1-0.4.5-py2.py3-none-any.whl (73kB)
    100% |████████████████████████████████| 81kB 8.2MB/s 
Collecting pyasn1-modules>=0.0.5 (from oauth2client)
  Downloading https://files.pythonhosted.org/packages/da/98/8ddd9fa4d84065926832bcf2255a2b69f1d03330aa4d1c49cc7317ac888e/pyasn1_modules-0.2.4-py2.py3-none-any.whl (66kB)
    100% |████████████████████████████████| 71kB 10.5MB/s 
Collecting rsa>=3.1.4 (from oauth2client)
  Downloading https://files.pythonhosted.org/packages/02/e5/38518af393f7c214357079ce67a317307936896e961e35450b70fad2a9cf/rsa-4.0-py2.py3-none-any.whl
Collecting cachetools>=2.0.0 (from google-auth>=1.4.1->google-api-python-client)
  Downloading https://files.pythonhosted.org/packages/39/2b/d87fc2369242bd743883232c463f28205902b8579cb68dcf5b11eee1652f/cachetools-3.1.0-py2.py3-none-any.whl
b2 1.3.8 has requirement arrow<0.12.1,>=0.8.0, but you'll have arrow 0.12.1 which is incompatible.
Installing collected packages: six, python-dateutil, httplib2, uritemplate, pyasn1, pyasn1-modules, cachetools, rsa, google-auth, google-auth-httplib2, google-api-python-client, oauth2client
  Running setup.py install for httplib2 ... done
Successfully installed cachetools-3.1.0 google-api-python-client-1.7.8 google-auth-1.6.2 google-auth-httplib2-0.0.3 httplib2-0.12.0 oauth2client-4.1.3 pyasn1-0.4.5 pyasn1-modules-0.2.4 python-dateutil-2.7.5 rsa-4.0 six-1.12.0 uritemplate-3.0.0
~  $  google_calendar.py
bash: google_calendar.py: command not found
~  $  cd ~/.cinnamon/configs/googleCalendar@javahelps.com
~/.cinnamon/configs/googleCalendar@javahelps.com  $  python3 ~/.local/share/cinnamon/desklets/googleCalendar@javahelps.com/py/google_calendar.py --list-calendars
[Names of various calendars]
```

I then ran the applet, which resulted in the screen flashing and nothing else happening.

**Comment by slgobinath** [comment]
According to the xsession log there is no error in the desklet part. We need to figure out why the Python script does not print any events.

Could you please check your Google Calendar in the browser for events in the next 7 days. If you don't have any events this behavior is expected.

**Comment by LinuxOnTheDesktop** [comment]
Thanks. I have events within the next seven days - at least in one calendar: I have multiple calendars. When trying to set up the desklet I did specify what I believe is the right calendar.

Also: upon running the Python command again - after opening Google Calendar in a browser - I get this output:


```
$ python3 ~/.local/share/cinnamon/desklets/googleCalendar@javahelps.com/py/google_calendar.py/usr/local/lib/python3.6/dist-packages/oauth2client/_helpers.py:255: UserWarning: Cannot access calendar.dat: No such file or directory
  warnings.warn(_MISSING_FILE_MESSAGE.format(filename))

Your browser has been opened to visit:

    https://accounts.google.com/o/oauth2/auth?<redacted>

If your browser is on a different machine then exit and re-run this
application with the command-line parameter

  --noauth_local_webserver
```

It is perhaps worth noting the following. (1) I use a VPN. (2) My Firefox uses a proxy connected to the VPN. (4) Firefox is my default browser. (4) I use Google Calendar via the Iridium browser (a Chromium-based browser).

**Comment by LinuxOnTheDesktop** [comment]
Having deleted `calendar.dat`, disabled my vpn, and set Iridium (which does not use a proxy - a proxy that only works when the vpn is up) as my default browser, and authenticated, the desklet appeared. The text of the desklet said: 'no events'. I discover that when I set the desklet to my original Google calendar, everything works. However, when I set the desklet to use the Google Calendar that I actually use, 'no events' is displayed (but there are events). I tried giving the desklet, not the 'name' of the calendar, but instead the calendar's Google 'calendar id' but that did not help.

**Comment by LinuxOnTheDesktop** [comment]
> In the desklet configuration, please provide a calendar name from the list of calendars printed by the following command

Yes, I have been doing that.

> If you leave calendar names field empty (which means retrieve from all calendars) in the desklet configuration, do you get events from your desired calendar?

No. Rather I continue to see 'no events found'.

Perhaps I should add that my main calendar's name is simply: 'NJ'.
